export const authConstants = {
  LOGIN_ATTEMPT: "LOGIN_ATTEMPT",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_ATTEMPT: "REGISTER_ATTEMPT",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGOUT_SUCCESS:"LOGOUT_SUCCESS",

  SET_USER: "SET_USER",
};
